spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWD}
      timeout: 6000ms
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.whu.pojo.entity
  configuration:
    map-underscore-to-camel-case: true

whu:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: ${JWT_SECRET_KEY:yuqiu}
    # 设置jwt过期时间
    ttl: 7200000
    # 设置前端传递过来的令牌名称
    token-name: token
  minio:
    endpoint: ${MINIO_ENDPOINT}
    accesskey: ${MINIO_ACCESS_KEY}
    secretkey: ${MINIO_SECRET_KEY}
    bucket: ${MINIO_BUCKET}
server:
  port: ${SERVER_PORT:8080}
